# Generated by Django 4.2.5 on 2023-09-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
