# Generated by Django 4.2.5 on 2023-09-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='details',
            new_name='body',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
