# Generated by Django 4.2.5 on 2023-10-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_gallery_galleryitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='galleryitem',
            old_name='gallery_id',
            new_name='gallery',
        ),
    ]
