# Generated by Django 4.2.5 on 2023-09-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_project_id_gallery_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumb',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
