# Generated by Django 4.2.5 on 2023-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_galleryitem_height_galleryitem_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
