# Generated by Django 4.2.5 on 2023-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_galleryitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True)]},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True)]},
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
