# Generated by Django 4.2.5 on 2023-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_favicon_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
